In [1]:
import random
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error


def hypothesis(theta, x):
    return np.dot(theta, x)


In [2]:
def mean_squared_error_(y_true: np.array, y_pred: np.array) -> float:
    return np.mean((y_true - y_pred)**2)/2


In [4]:
matr: np.array = np.array([[1, 1], [1, 1]])  # for example
w = np.array([random. uniform(-5, 5) for i in range(matr.shape[1] + 1)])  # starting coeffs for calculating

def one_step_gradient(x: np.array, y: np.array, w: np.array, lr: float = 0.001): # realization see below
    m = len(y)
    h = np.dot(w, x.transpose())
    w = w - lr * np.dot(x.transpose(), (h - y)) / m
    return w


In [5]:
path = "Housing.csv"
data = pd.read_csv(path)
data

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]

In [6]:
columns = ["area", "bedrooms", "bathrooms"]
data_new = data[columns]

In [7]:
m = np.array(data_new)
m

array([[7420,    4,    2],
       [8960,    4,    4],
       [9960,    3,    2],
       ...,
       [3620,    2,    1],
       [2910,    3,    1],
       [3850,    3,    1]], dtype=int64)

In [8]:
matr_X = data_new.values

print(len(matr_X), matr_X.shape)

545 (545, 3)


In [10]:
matr_y = np.array(data["price"])
print(len(matr_y))

545


In [11]:
matr_X[109:]

array([[6615,    4,    2],
       [6600,    3,    1],
       [8372,    3,    1],
       ...,
       [3620,    2,    1],
       [2910,    3,    1],
       [3850,    3,    1]], dtype=int64)

In [15]:
w = np.array([random. uniform(-5, 5) for i in range(matr_X.shape[1] + 1)])
w

array([-4.06335325, -4.80073237,  4.4187388 ,  2.92254276])

In [16]:
add_matr = np.ones((len(matr_X), 1))
X = np.concatenate((add_matr, matr_X), axis=1)
res_one = one_step_gradient(X, matr_y, w)
res_one

array([4.78737947e+03, 2.68727695e+07, 1.47178869e+04, 6.65238917e+03])

In [18]:
model = LinearRegression()
regressor_task = model.fit(matr_X[109:], matr_y[109:])

print(regressor_task.coef_)
print(regressor_task.intercept_)

y_pred_test = model.predict(matr_X[:109])
print(y_pred_test)
print("Mean squared error: %.2f" % mean_squared_error(matr_y[:109], y_pred_test))
print(regressor_task.predict(np.array([[7420, 4, 2]])))
# [1.40146963e+06 2.39630763e+02 3.01147193e+05 5.33804306e+05] - from analytical resolve

[2.39630763e+02 3.01147193e+05 5.33804306e+05]
1401469.6293651261
[5451727.27391723 6888367.26029907 5759242.21789589 5470897.73493511
 4917922.9680234  5703554.84748991 6263503.26457031 8390636.8698624
 5080871.88667538 4750396.70682996 6001841.58322621 5645255.89674369
 5243248.51034778 4512374.68404111 5241639.77041314 4577647.28495603
 5255230.04848396 5409381.30431958 4474821.32969794 4910949.31785471
 3873920.41024153 5087077.92845648 4767743.15520019 4465236.099189
 5481270.53313664 5240852.20272055 4810304.39751084 4965438.53444707
 5879878.7714997  4991636.20948811 5163759.772528   4516130.85434051
 4843065.13659954 5334523.47289572 5080084.31898279 5049935.16023434
 5165437.18786706 5830343.87902036 4276500.09161701 5111451.59084986
 4408297.01111494 4896571.4720913  4925327.16361812 5111451.59084986
 5111451.59084986 4810304.39751084 4810304.39751084 4420278.54925111
 4402932.10088089 5155372.69583268 5155372.69583268 4354380.08950215
 5111451.59084986 4606618.24919586 48103

In [ ]:
# Analytical resolving

In [25]:
add_matr = np.ones((len(matr_X[109:]), 1))
# add_matr

In [26]:
X = np.concatenate((add_matr, matr_X[109:]), axis=1)
print(X)

[[1.000e+00 6.615e+03 4.000e+00 2.000e+00]
 [1.000e+00 6.600e+03 3.000e+00 1.000e+00]
 [1.000e+00 8.372e+03 3.000e+00 1.000e+00]
 ...
 [1.000e+00 3.620e+03 2.000e+00 1.000e+00]
 [1.000e+00 2.910e+03 3.000e+00 1.000e+00]
 [1.000e+00 3.850e+03 3.000e+00 1.000e+00]]


In [27]:
# (XT*X)^(-1)

A = np.linalg.inv(np.dot(X.transpose(), X))
print(np.dot(A, np.dot(X.transpose(), X)))

[[ 1.00000000e+00  2.54658516e-11  0.00000000e+00  8.88178420e-16]
 [-1.08420217e-19  1.00000000e+00 -9.48676901e-20 -8.13151629e-20]
 [-8.88178420e-16 -6.36646291e-12  1.00000000e+00 -2.22044605e-16]
 [ 0.00000000e+00 -7.27595761e-12  3.55271368e-15  1.00000000e+00]]


In [29]:
w = np.dot(A, np.dot(X.transpose(), matr_y[109:]))
print(w)


[1.40146963e+06 2.39630763e+02 3.01147193e+05 5.33804306e+05]


In [23]:
predict = np.dot(w, X.transpose())
predict

array([ 7036627.15462756, 10392020.79073061,  7591864.51496454,
        7066928.17491437,  5650577.65683657,  8046157.63893618,
        8862041.44657728, 12155033.66266495,  5908136.32927444,
        5997273.32237125,  7433006.33878927,  7884833.54232771,
        6707103.55900852,  5551877.16057396,  6773736.96722071,
        5112734.54674572,  6726041.69668778,  7038870.89473029,
        5561696.15574839,  6251044.36727327,  4069593.08695356,
        6529434.99115832,  5482378.15782599,  5546545.64560498,
        7152499.72080582,  6703315.93147267,  6091964.01076753,
        5794857.42953371,  7644191.44779686,  6309402.66774417,
        6650639.07230556,  5084677.26656164,  6074569.7605214 ,
        7462862.99841512,  5837715.2935264 ,  6470726.76435263,
        6653290.41158065,  7635072.30529203,  4705914.51297653,
        6498784.04453672,  4914234.02744834,  6228318.60205817,
        6273770.13248838,  6498784.04453672,  6498784.04453672,
        6091964.01076753,  6091964.01076

In [31]:
y_pred = model.predict(matr_X)
res = mean_squared_error_(predict, matr_y)
res

895585024988.6597

In [ ]:
# 1401469.6293651261 2.39630763e+02 3.01147193e+05 5.33804306e+05 - sklearn resolve

# [1.40146963e+06 2.39630763e+02 3.01147193e+05 5.33804306e+05] - analytical resolve